### ISSUE TITLE
issue_jaulent

### ISSUE THREAD

**Issue by Julien-Jaulent** [clementfoltran/projectHone#10]
Quel est le problème?
A partir d'un tweet récupéré en paramètre retourner la polariter tu tweet

Comment cela peut-il être résolu?

Faire la fonction orientée objet en utilisant le même modèle que la fonction d'Antoine.
Pour tester je vais placer des Fakevalues

Etiquettes
Python.

Important
Rien à signaler pour le moment.

**Comment by silviodc** [comment]
Salut @Julien-Jaulent,

Trouve ici mes commentaires

> En ajoutant une librairie que je n'avais pas pu ajouter en cours

Pourriez-vous être plus précis?

> creer des URL pour qu'a l'appel des fonctions tout le monde puisse les utiliser

Manon a écrit la même chose! #6 

Je vous suggère de transformer les données que vous avez pris à l'ajustement avec la classe [Twitter](https://github.com/clementfoltran/projectHone/blob/manon.vincent/server/myapp/tweet.py)

**Comment by marie-ototoi** [comment]
@Julien-Jaulent @alex-matias  
Ce que Julien peut faire pour que vous puissiez "brancher" le front au back sans attendre que Julien ait fini : 

Julien, provisoirement en haut de la fonction définie dans rest-server.py, tu mets : 

listFakeValues = [-1, -0.4, -0.1, 0.2, 0.7, 1]
//ici tu selectionnes une des fake value en randon
randomValue = ...
return randomValue

et puis en dessous tu fais l'appel à ta classe, plus tard tu n'auras plus qu'à commenter les trois premieres lignes
en attendant le front récupèrera des valeurs différentes qui lui permettront d'avancer

demande à Antoine comment il s'y prend pour tester sa classe en attendant qu'elle soit branchée (il met les fonctions d'appel provisoirement à la fin de la classe je crois)
