### ISSUE TITLE
Création de statistiques - Python

### ISSUE THREAD

**Issue by ohanqo** [clementfoltran/projectHone#3]
### ** Quel est le problème ? **
Créer la partie statistique des tweets concernant un hashtag particulier choisi par l’équipe de développement. Les statistiques devront être regroupées par région. Le but est d'obtenir des valeurs caractérisant chaque région en fonction du nombre de tweets, likes, retweets ainsi que leurs polarités.

### ** Comment cela peut-il être résolu ? **

1. Utiliser la librairie Pandas pour manipuler & organiser les données.

2. Utiliser le package NumPy pour extraire sous forme de tableau les informations souhaitées.

3. Récupérer la polarité avec Textblob.

3. Écrire le tout dans un fichier json.
 
### ** Qui peut m'aider avec ce problème ? **
Tout le monde

### ** Étiquettes **
python-code

### ** Important **
Chaque tweet doit posséder une région comme attribut.

**Comment by silviodc** [comment]
Salut @ohanqo 

Que pensez-vous de faire la méthode pour simplement prendre un hashtag et récupérer les statistiques, au lieu de hashtags prédéterminés?

Plus tard, nous pouvons prendre ces hashtags à partir de fichiers .txt déterminés, par exemple.

**Comment by ohanqo** [comment]
Bonjour @silviodc 

Je pense que c'est une bonne idée. Je vais essayer de faire ça.

Merci bien

**Comment by ohanqo** [comment]
Bonjour,

Pour récupérer/afficher les statistiques d'un hashtag, on doit utiliser l'url suivante :
[http://localhost:5001/statistics?hashtag=Oscars](http://localhost:5001/statistics?hashtag=Oscars)

Un exemple du json obtenu pour 4 tweets avec l'hashtag Oscars :
`{"Content":"RT @nbaextra: Kobe Bryant ajoute un titre \u00e0 sa collection... \n#legend #oscars https:\/\/t.co\/dI7CuiBv5E","Date":1520277554000,"Retweets":367,"Likes":0} {"Content":"RT @Marmeladeapp: Lequel de ces deux Spider-Man est le meilleur ?\ud83d\udd78\ufe0f\n#TwitteriseUnFilm #Oscars\n\n\ud83d\udd04 Pour Spider-Man\n\u2764\ufe0f Pour The Amazing Spider\u2026","Date":1520277536000,"Retweets":325,"Likes":0} {"Content":"RT @nbaextra: Un #Oscar pour Kobe Bryant !\n#Oscars #NBAextra https:\/\/t.co\/njG0vXedLh","Date":1520277545000,"Retweets":96,"Likes":0} {"Content":"#Oscars Il \u00e9tait vu comme l'un des favoris des Oscars avec ses 5 nominations, Dunkerque de Christopher Nolan a en e\u2026 https:\/\/t.co\/Ri7PD0hcYP","Date":1520277553000,"Retweets":0,"Likes":0}`

**Comment by ohanqo** [comment]
Bonjour,

Pour récupérer/afficher les statistiques d'un hashtag :
[http://localhost:5001/statistics/hashtag/Oscars
](http://localhost:5001/statistics/hashtag/Oscars
)

Pour récupérer/afficher les statistiques d'une région (à partir d'un code de région) :
[http://localhost:5001/statistics/region/94](http://localhost:5001/statistics/region/94)

Exemple du json rendu (un seul tweet) :
`{
  "statistics": {
    "0": {
      "Content": "RT @DisneyFR: F\u00e9licitations \u00e0 #Coco qui a remport\u00e9 l'Oscar du Meilleur Film d'Animation et l'Oscar de la Meilleure Chanson Originale ! #Osc\u2026", 
      "Date": "Thu, 08 Mar 2018 20:19:06 GMT", 
      "Likes": 0, 
      "Retweets": 402
    }
  }
}`

**Comment by marie-ototoi** [comment]
Super, tu avances bien !
J'ai oublié de te dire que quand tu ajoutes une lib Python (pandas), il faut que tu penses à la rajouter à la config docker, pour que ça marche chez les autres. C'est dans le fichier requirements.txt dans le répertoire server. Pour Panda Julien l'a fait hier car c'est ce qui faisait bugger son install, je te le dis pour une prochaine lib ou un prochain projet.

Pour la suite, tu peux regarder mon commentaire sur https://github.com/clementfoltran/projectHone/issues/7. Si ça t'intéresse tu pourrais essayer de créer les composants pour que les autres mettent ensuite leur code dedans. Sinon il faudra peut-être donner un coup de main à Alexandre ou Julien. Ou tu peux regarder les issues non attribuées et voir ce qui te plaît.

**Comment by ohanqo** [comment]
Bonjour,

J'ai une erreur qui apparaît quelques fois lors d'un appel avec les urls. Et j'aurais besoin d'aide concernant sa résolution. L'erreur en question est :
```
builtins.TypeError
TypeError: '<' not supported between instances of 'str' and 'int'
```
Cette erreur apparaît aléatoirement et est provoquée par la ligne permettant de transformer le dictionnaire en json avec jsonify.
```
json = jsonify({'statistics':result})
```

**Comment by silviodc** [comment]
Bonjour @ohanqo,

Êtes-vous en train d'essayer de convertir le pandas dataframe directement?

**Comment by ohanqo** [comment]
Non pas directement, ce que je ne comprends pas c'est que des fois cela fonctionne et des fois ça ne marche pas et génère une erreur.

Voilà mon code pour la route : 
```
@app.route('/statistics/hashtag/<hashtagSearched>')
@cross_origin()
def getStatistics(hashtagSearched):
    statistics = Statistics(hashtagSearched)
    df = statistics.retrieveStatistics()
    result = df.to_dict(orient='index')
    # fix key error string
    for key in result.keys():
        if type(key) is not str:
            try:
                result[str(key)] = result[key]
            except:
                try:
                    result[repr(key)] = result[key]
                except:
                    pass
            del result[key]
    print(result)
    json = jsonify({'statistics':result})
    return json
```

**Comment by silviodc** [comment]
Salut @ohanqo ,

Essayez de remplacer votre boucle, pour le code suivant.

`result = {str(k):v for k,v in result.items()}`

**Comment by ohanqo** [comment]
Ça marche 👍 

Merci bien @silviodc
