### ISSUE TITLE
Issue_D3-Kévin_Coloration-de-la-carte

### ISSUE THREAD

**Issue by kdrh** [clementfoltran/projectHone#9]
**Quel est le problème?**
Colorer la carte en fonction des humeurs résultant de l'analyse des tweets réalisée par l'équipe Python.

**Comment cela peut-il être résolu?**
* Examiner le code existant et en extraire les principales commandes qui pourront être utiles à la modification des couleurs de la carte ;
* Chercher un moyen d'extraire les données issues des scripts Python ;
* Mettre en place une structure conditionnelle qui serait en mesure d'adapter les couleurs en fonction des sentiments générés par les algorithmes de recherche.

**Qui peut m'aider avec ce problème ?**
Jusqu'au samedi 3 mars 2018, je vais faire en sorte de remédier à ce dernier. Passé ce délai, tout le monde pourra m'aider.

**Etiquettes**
D3 et potentiellement Python.

**Important**
Rien à signaler pour le moment.

**Comment by marie-ototoi** [comment]
Ok ! essaie d'identifier plus précisément :
- qui dans l'équipe Python peut te donner l'url à appeler et le format de la réponse (c'est à dire les clés JSON)
- comment on fait en JS pour appeler une URL et utiliser la réponse (là-dessus je pense qu'Othmane peut t'aider par exemple il me semble qu'il l'a fait la dernière fois)

**Comment by kdrh** [comment]
Merci pour ces indications ! Je vais me renseigner et je vous tiendrais au courant dès que possible.

**Comment by silviodc** [comment]
Je suggère aussi de regarder les commentaires de l'issue #2
Ça pourrait donner des idées pour avancer un peu.
